### PR TITLE
Preserve the reason when deferring a loaded source event

### LINKED ISSUE #145: Adapter not sending "removed" loadedSource events on page refresh.
The adapter should be sending the "removed" loadedSource events when the page is refreshed to clear out old scripts, but it does not. This results in duplicated scripts in the scripts view while debugging (in Visual Studio only).

- VS Code Version: N/A
- Log file (set `"trace": true` in launch config):

Steps to reproduce:

1. Launch Edge with debugging
2. See in the logs that the loadedSource events with "removed" are never sent after a page refresh.

### PR DESCRIPTION
**Pull request by EricCornelson**
Fixes #145

### CODE REVIEW

File: src/legacyEdge/edgeDebugAdapter.ts [hunk 1]
```diff
@@ -364,22 +364,23 @@ export class EdgeDebugAdapter extends CoreDebugAdapter {
...
         // This is done because in case of quick refreshes, we end up sending 'changed' events for new scripts because
         // scriptParsedEventBookKeeping hasn't been refreshed yet
         if (!this._navigationInProgress) {
-            let loadedSourceReason: LoadedSourceEventReason;
-            if (!this._scriptParsedEventBookKeeping[script.scriptId]) {
-                this._scriptParsedEventBookKeeping[script.scriptId] = true;
-                loadedSourceReason = 'new';
-            } else {
-                loadedSourceReason = 'changed';
+            if (!reason) {
```
Comment (dhanvikapila) [inline src/legacyEdge/edgeDebugAdapter.ts]: What is the reason we receive from Edge if its not 'new' or 'changed'?

Comment (EricCornelson) [reply src/legacyEdge/edgeDebugAdapter.ts]: We don't get any reason from Edge directly. We get one or more `ScriptParsedEvent` events from Edge, and if we haven't seen a parse event for that script yet, we send the `LoadedSourceEvent` to VS/VS code with reason "new", and if we have seen it before, we send it with reason "changed".

The other possible reason is "removed", which we send after we get the `Runtime.executionContextsCleared` event from Edge.
